### ISSUE TITLE
Move the NPM auth token outside of `npm/npmrc`

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/dotfiles#3]
Right now, Git wants to track my NPM auth token that is actually private information. This problem [has been discussed on `npm/npm`](https://github.com/npm/npm/issues/4905). [A workaround has been proposed by `othiym23`](https://github.com/npm/npm/issues/8223).

**Comment by mightyiam** [comment]
Same problem in my dotfiles. How did you solve it?

**Comment by derhuerst** [comment]
I haven't solved it yet in fact. I just don't commit it. I will try the proposed solution however.

**Comment by mightyiam** [comment]
This works for me:
https://github.com/mightyiam/dotfiles/commit/94b653449e36b2ce3f15fa705cef7b6380e31b63

And the `.npmrc` has only the secret.

**Comment by derhuerst** [comment]
Thanks!
